name: 'statix-action'
description: 'Lint Nix code, and optionally create a pull request'
inputs:
  action:
    description: 'statix action'
    required: false
    default: 'check'
  directory:
    description: 'Directory on which to run statix'
    required: false
    default: '.'
  create_pr:
    description: 'Whether to create a PR'
    required: false
    default: 'false'
  commit_message:
    description: 'Commit message'
    required: false
    default: 'Lint Nix code'
runs:
  using: "composite"
  steps:
    - name: Lint Nix code
      run: 'nix run nixpkgs#statix -- ${{ inputs.action }} ${{ inputs.directory }}'
      shell: bash
      id: statix
    - name: Create PR
      if: inputs.create_pr == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        branch: statix-lint
        delete-branch: true
        title: "${{ inputs.commit_message }}"
        commit-message: "${{ inputs.commit_message }}"
        body: |
          Automated linting performed by the [statix-action](https://github.com/jocelynthode/statix-action) GitHub Action.
branding:
    icon: 'check-circle'
    color: 'green'
